version: "3.8"
services:
  profile-scrape-db:
    container_name: profile-scrape-db
    image: mysql:8.0.26
    ports:
      - 3306:3306
    volumes:
      - profile-scrape-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 11
      MYSQL_USER: moblytics
      MYSQL_PASSWORD: moblytics
      MYSQL_DATABASE: moblytics

volumes:
  profile-scrape-vol: